import Head from "next/head";
import { useEffect } from "react";

export default function Login() {
  useEffect(() => {
    require("@passageidentity/passage-elements/passage-auth");
  }, []);

  const appID = process.env.NEXT_PUBLIC_APP_ID

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex h-screen items-center justify-center">
        <div className="w-full min-w-[200px] p-4 md:min-w-[400px]">
          <passage-auth app-id={appID}></passage-auth>
        </div>
      </div>
    </div>
  );
}
